version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ccna_user
      POSTGRES_PASSWORD: ccna_password
      POSTGRES_DB: ccna_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
